name: Example CMake

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 3'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          install: git make mingw-w64-x86_64-toolchain mingw-w64-x86_64-qt5 mingw-w64-x86_64-qtwebkit
      - run: qmake
      - run: sed 's/windres -i/windres --codepage=65001 -i/g' -i Makefile.Release
      - run: make release

