name: Build with gcc in windows

on:
  push:
    branches:
      - GA

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          install: git make mingw-w64-x86_64-toolchain mingw-w64-x86_64-qt5 mingw-w64-x86_64-qtwebkit
      - run: qmake
      - run: sed 's/windres -i/windres --codepage=65001 -i/g' -i Makefile.Release
      - run: make release
      - run: la -al release/target/
      - run: bash -c 'path=$(dirname "release/target/QuiteRSS.exe"); list=$(ldd.exe $1 | grep mingw | awk '{split($0,a," "); print a[3]}'); IFS=$'\n' read -rd '' -a array <<< $list; for element in "${array[@]}";do cp "$element" $path/ done;'
      - run: windeployqt --no-opengl-sw --no-angle --no-system-d3d-compiler --no-translations --force release/target/QuiteRSS.exe
      - run: la -al release/target/